### ISSUE TITLE
Pull request #106 has a bug 

### ISSUE THREAD

**Issue by eternal44** [excid3/simple_calendar#109]
The latest (pull request)[https://github.com/excid3/simple_calendar/commit/fe555703680d621d201f4571dcb4622b8f213bdd] has a bug.  When a month calendar loops through events it dumps all of it's params into the view (erb).

**Comment by klipie245** [comment]
I just tested this out with the month calendar, it works fine on my side. Can you maybe attach a screenshot?

**Comment by excid3** [comment]
Interesting, not sure how that one would have caused that issue. I'd love to hear some more details about what you're using. Are you using Haml?

**Comment by eternal44** [comment]
@excid3  Hey Chris - I only used html.erb.

@klipie245 Check out my screenshot below.  The only unusual environment config I can think of is I'm using Chris' [multitenancy setup](https://gorails.com/episodes/subdomains-and-multi-tenancy-from-scratch) which shouldn't be an issue...

![issue_ 106](https://cloud.githubusercontent.com/assets/4598088/9861070/0a1240a4-5ae5-11e5-9d1b-2a8465d2febb.png)

**Comment by excid3** [comment]
@eternal44 I fixed a bug in 2.0.0 and released 2.0.1 which fixed this I think. I had an extra `<%=` when it should have been `<%` in the view. Try doing a bundle update and restart your app to see if that fixes it for you. Fingers crossed, that was the problem!

**Comment by eternal44** [comment]
@excid3 I wish I found that error!  I'm still getting familiar gems and hope to make bigger contributions soon.  

I'm not getting the update yet [(ruby gems)](https://rubygems.org/gems/simple_calendar).  Is there another way I should be checking for the new release?

**Comment by excid3** [comment]
Hahaha so...I forgot to publish the new version. 2.0.1 is out now. :wink:

And no worries! I'll try to leave some easy fixes out for people to fix in the future!

**Comment by klipie245** [comment]
@eternal44 It seems that it is now on [Ruby Gems](https://rubygems.org/gems/simple_calendar). Try doing a bundle update now and then restarting the app. Should work :)

**Comment by eternal44** [comment]
Issue resolved - thanks Chris!  Sorry for the delay.

**Comment by excid3** [comment]
@eternal44 Ha! Glad that fixed it for you. :)
